<?php
// database/seeders/ProductSeeder.php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ==================== MAKANAN RINGAN (Category 1) ====================
            [
                'category_id' => 1,
                'name' => 'Chitato Sapi Panggang 60g',
                'slug' => 'chitato-sapi-panggang-60g',
                'description' => 'Keripik kentang rasa sapi panggang yang renyah dan gurih. Terbuat dari kentang pilihan dengan bumbu berkualitas.',
                'price' => 15000,
                'stock' => 45,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2022/3/15/0cd2c5be-edf4-4839-9d28-28fbc5cb5fa5.jpg',
            ],
            [
                'category_id' => 1,
                'name' => 'Oreo Original 133g',
                'slug' => 'oreo-original-133g',
                'description' => 'Biskuit sandwich dengan krim vanilla yang lembut. Cocok untuk cemilan keluarga.',
                'price' => 10000,
                'stock' => 60,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/7/5/4c2f4a1e-8b5e-4d2c-b5a8-f8c5a1b5e9d3.jpg',
            ],
            [
                'category_id' => 1,
                'name' => 'Tango Wafer Vanilla 130g',
                'slug' => 'tango-wafer-vanilla-130g',
                'description' => 'Wafer renyah dengan krim vanilla yang manis dan gurih. Camilan ringan yang cocok untuk segala suasana.',
                'price' => 8000,
                'stock' => 35,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/3/12/a1b2c3d4-e5f6-7890-abcd-ef1234567890.jpg',
            ],
            [
                'category_id' => 1,
                'name' => 'Lays Rumput Laut 68g',
                'slug' => 'lays-rumput-laut-68g',
                'description' => 'Keripik kentang tipis dengan taburan rumput laut yang gurih. Renyah dan bikin ketagihan.',
                'price' => 14000,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2022/6/20/f1e2d3c4-b5a6-7890-cdef-1234567890ab.jpg',
            ],
            [
                'category_id' => 1,
                'name' => 'Qtela Singkong Balado 80g',
                'slug' => 'qtela-singkong-balado-80g',
                'description' => 'Keripik singkong renyah dengan bumbu balado pedas. Camilan tradisional dengan rasa modern.',
                'price' => 9000,
                'stock' => 50,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/8/15/1a2b3c4d-5e6f-7890-abcd-ef1234567890.jpg',
            ],

            // ==================== MINUMAN (Category 2) ====================
            [
                'category_id' => 2,
                'name' => 'Coca Cola 390ml',
                'slug' => 'coca-cola-390ml',
                'description' => 'Minuman bersoda rasa cola yang menyegarkan. Cocok diminum dingin saat cuaca panas.',
                'price' => 8000,
                'stock' => 120,
                'min_stock' => 20,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/5/10/2b3c4d5e-6f7a-8901-bcde-f12345678901.jpg',
            ],
            [
                'category_id' => 2,
                'name' => 'Aqua 600ml',
                'slug' => 'aqua-600ml',
                'description' => 'Air mineral alami dari pegunungan. Diproses secara higienis untuk kesegaran optimal.',
                'price' => 4000,
                'stock' => 200,
                'min_stock' => 30,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/1/1/3c4d5e6f-7a8b-9012-cdef-123456789012.jpg',
            ],
            [
                'category_id' => 2,
                'name' => 'Teh Botol Sosro 450ml',
                'slug' => 'teh-botol-sosro-450ml',
                'description' => 'Minuman teh asli Indonesia dalam kemasan botol. Teh berkualitas dengan rasa yang khas.',
                'price' => 6000,
                'stock' => 85,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2019/12/25/4d5e6f7a-8b9c-0123-def4-567890abcdef.jpg',
            ],
            [
                'category_id' => 2,
                'name' => 'Pocari Sweat 500ml',
                'slug' => 'pocari-sweat-500ml',
                'description' => 'Minuman isotonik pengganti cairan tubuh. Mengembalikan ion yang hilang setelah beraktivitas.',
                'price' => 10000,
                'stock' => 70,
                'min_stock' => 12,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/7/15/5e6f7a8b-9c0d-1234-ef56-7890abcdef01.jpg',
            ],
            [
                'category_id' => 2,
                'name' => 'Kopi Kapal Api 25g',
                'slug' => 'kopi-kapal-api-25g',
                'description' => 'Kopi bubuk sachet dengan cita rasa khas Indonesia. Praktis dan nikmat diseduh kapan saja.',
                'price' => 2500,
                'stock' => 150,
                'min_stock' => 25,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2019/6/10/6f7a8b9c-0d1e-2345-f678-90abcdef0123.jpg',
            ],

            // ==================== KEBUTUHAN POKOK (Category 3) ====================
            [
                'category_id' => 3,
                'name' => 'Beras Premium 5kg',
                'slug' => 'beras-premium-5kg',
                'description' => 'Beras kualitas premium yang pulen dan wangi. Cocok untuk konsumsi sehari-hari keluarga.',
                'price' => 75000,
                'stock' => 40,
                'min_stock' => 8,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/1/20/7a8b9c0d-1e2f-3456-7890-abcdef012345.jpg',
            ],
            [
                'category_id' => 3,
                'name' => 'Gula Pasir 1kg',
                'slug' => 'gula-pasir-1kg',
                'description' => 'Gula pasir putih premium, bersih dan higienis. Cocok untuk pemanis minuman dan masakan.',
                'price' => 16000,
                'stock' => 80,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/8/5/8b9c0d1e-2f34-5678-90ab-cdef01234567.jpg',
            ],
            [
                'category_id' => 3,
                'name' => 'Minyak Goreng Bimoli 2L',
                'slug' => 'minyak-goreng-bimoli-2l',
                'description' => 'Minyak goreng kemasan 2 liter. Minyak berkualitas untuk memasak sehari-hari.',
                'price' => 42000,
                'stock' => 35,
                'min_stock' => 8,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/4/10/9c0d1e2f-3456-7890-abcd-ef0123456789.jpg',
            ],
            [
                'category_id' => 3,
                'name' => 'Tepung Terigu Segitiga Biru 1kg',
                'slug' => 'tepung-terigu-segitiga-biru-1kg',
                'description' => 'Tepung terigu serbaguna untuk aneka kue dan masakan. Berkualitas premium.',
                'price' => 14000,
                'stock' => 50,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2019/9/30/0d1e2f34-5678-90ab-cdef-0123456789ab.jpg',
            ],

            // ==================== PERLENGKAPAN MANDI (Category 4) ====================
            [
                'category_id' => 4,
                'name' => 'Sabun Mandi Lifebuoy 100g',
                'slug' => 'sabun-mandi-lifebuoy-100g',
                'description' => 'Sabun mandi kesehatan dengan perlindungan antibakteri. Membersihkan dan menjaga kesehatan kulit.',
                'price' => 5000,
                'stock' => 120,
                'min_stock' => 20,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/3/20/1e2f3456-7890-abcd-ef01-234567890abc.jpg',
            ],
            [
                'category_id' => 4,
                'name' => 'Sampo Sunsilk 170ml',
                'slug' => 'sampo-sunsilk-170ml',
                'description' => 'Sampo untuk rambut sehat, lembut, dan berkilau. Mengandung nutrisi untuk akar rambut.',
                'price' => 18000,
                'stock' => 45,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/11/5/2f345678-90ab-cdef-0123-4567890abcde.jpg',
            ],
            [
                'category_id' => 4,
                'name' => 'Pasta Gigi Pepsodent 190g',
                'slug' => 'pasta-gigi-pepsodent-190g',
                'description' => 'Pasta gigi dengan fluoride untuk gigi kuat dan sehat. Mencegah gigi berlubang.',
                'price' => 22000,
                'stock' => 55,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/5/1/34567890-abcd-ef01-2345-67890abcdef0.jpg',
            ],
            [
                'category_id' => 4,
                'name' => 'Sikat Gigi Formula',
                'slug' => 'sikat-gigi-formula',
                'description' => 'Sikat gigi berkualitas dengan bulu sikat lembut. Membersihkan gigi dan gusi secara optimal.',
                'price' => 12000,
                'stock' => 80,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2019/2/14/4567890a-bcde-f012-3456-7890abcdef01.jpg',
            ],

            // ==================== ALAT TULIS (Category 5) ====================
            [
                'category_id' => 5,
                'name' => 'Buku Tulis Sidu 38 Lembar',
                'slug' => 'buku-tulis-sidu-38-lembar',
                'description' => 'Buku tulis bergaris untuk keperluan sekolah dan kantor. Kertas berkualitas tebal.',
                'price' => 5000,
                'stock' => 200,
                'min_stock' => 30,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/10/15/567890ab-cdef-0123-4567-890abcdef012.jpg',
            ],
            [
                'category_id' => 5,
                'name' => 'Pulpen Standard AE7',
                'slug' => 'pulpen-standard-ae7',
                'description' => 'Pulpen tinta biru/hitam untuk menulis sehari-hari. Tinta lancar dan nyaman digenggam.',
                'price' => 3000,
                'stock' => 300,
                'min_stock' => 50,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2019/7/22/67890abc-def0-1234-5678-90abcdef0123.jpg',
            ],
            [
                'category_id' => 5,
                'name' => 'Pensil 2B Faber Castell',
                'slug' => 'pensil-2b-faber-castell',
                'description' => 'Pensil untuk menulis dan menggambar. Kualitas terbaik dengan grafit halus.',
                'price' => 4000,
                'stock' => 150,
                'min_stock' => 25,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/12/1/7890abcd-ef01-2345-6789-0abcdef01234.jpg',
            ],
            [
                'category_id' => 5,
                'name' => 'Buku Gambar A4',
                'slug' => 'buku-gambar-a4',
                'description' => 'Buku gambar ukuran A4 untuk menggambar dan mewarnai. Kertas putih tebal tidak tembus.',
                'price' => 10000,
                'stock' => 50,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/4/8/890abcde-f012-3456-7890-abcdef012345.jpg',
            ],

            // ==================== PRODUK KEBERSIHAN (Category 6) ====================
            [
                'category_id' => 6,
                'name' => 'Deterjen Rinso 900g',
                'slug' => 'deterjen-rinso-900g',
                'description' => 'Deterjen bubuk untuk mencuci pakaian. Membersihkan noda membandel dan memberikan kesegaran.',
                'price' => 20000,
                'stock' => 55,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/9/12/90abcdef-0123-4567-890a-bcdef0123456.jpg',
            ],
            [
                'category_id' => 6,
                'name' => 'Pembersih Lantai Super Pell 900ml',
                'slug' => 'pembersih-lantai-super-pell-900ml',
                'description' => 'Cairan pembersih lantai dengan aroma segar. Membersihkan dan memberikan keharuman pada lantai.',
                'price' => 18000,
                'stock' => 40,
                'min_stock' => 8,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2019/11/28/a0bcdef0-1234-5678-90ab-cdef01234567.jpg',
            ],
            [
                'category_id' => 6,
                'name' => 'Sabun Cuci Piring Sunlight 755ml',
                'slug' => 'sabun-cuci-piring-sunlight-755ml',
                'description' => 'Sabun cuci piring cair yang efektif menghilangkan lemak dan minyak. Lembut di tangan.',
                'price' => 15000,
                'stock' => 65,
                'min_stock' => 12,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/2/14/bcdef012-3456-7890-abcd-ef0123456789.jpg',
            ],

            // ==================== MAKANAN INSTAN (Category 7) ====================
            [
                'category_id' => 7,
                'name' => 'Indomie Goreng',
                'slug' => 'indomie-goreng',
                'description' => 'Mie instan goreng dengan bumbu khas Indonesia. Cepat disajikan dan lezat.',
                'price' => 3500,
                'stock' => 200,
                'min_stock' => 40,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2018/6/1/cdef0123-4567-890a-bcde-f01234567890.jpg',
            ],
            [
                'category_id' => 7,
                'name' => 'Indomie Kuah Ayam Bawang',
                'slug' => 'indomie-kuah-ayam-bawang',
                'description' => 'Mie instan kuah rasa ayam bawang yang gurih. Cocok untuk sarapan atau makan malam.',
                'price' => 3000,
                'stock' => 180,
                'min_stock' => 35,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2018/6/1/def01234-5678-90ab-cdef-012345678901.jpg',
            ],
            [
                'category_id' => 7,
                'name' => 'Mie Sedap Goreng',
                'slug' => 'mie-sedap-goreng',
                'description' => 'Mie instan goreng dengan bumbu dan kecap manis. Rasanya khas dan mengenyangkan.',
                'price' => 3500,
                'stock' => 150,
                'min_stock' => 30,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2018/6/1/ef012345-6789-0abc-def0-123456789012.jpg',
            ],
            [
                'category_id' => 7,
                'name' => 'Pop Mie Ayam',
                'slug' => 'pop-mie-ayam',
                'description' => 'Mie instan cup rasa ayam dengan topping sayuran. Praktis tinggal seduh.',
                'price' => 7000,
                'stock' => 80,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2018/6/1/f0123456-7890-abcd-ef01-234567890123.jpg',
            ],
            [
                'category_id' => 7,
                'name' => 'Sarden ABC 425g',
                'slug' => 'sarden-abc-425g',
                'description' => 'Ikan sarden dalam saus tomat siap makan. Sumber protein praktis untuk keluarga.',
                'price' => 18000,
                'stock' => 35,
                'min_stock' => 8,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/7/30/01234567-890a-bcde-f012-345678901234.jpg',
            ],

            // ==================== BUMBU DAPUR (Category 8) ====================
            [
                'category_id' => 8,
                'name' => 'Kecap Manis Bango 275ml',
                'slug' => 'kecap-manis-bango-275ml',
                'description' => 'Kecap manis berkualitas untuk penyedap masakan. Memberikan rasa manis gurih khas Indonesia.',
                'price' => 18000,
                'stock' => 70,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/7/15/12345678-90ab-cdef-0123-456789012345.jpg',
            ],
            [
                'category_id' => 8,
                'name' => 'Saus Sambal ABC 275ml',
                'slug' => 'saus-sambal-abc-275ml',
                'description' => 'Saus sambal botol dengan rasa pedas yang pas. Cocok untuk cocolan dan masakan.',
                'price' => 12000,
                'stock' => 85,
                'min_stock' => 15,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/7/15/23456789-0abc-def0-1234-567890123456.jpg',
            ],
            [
                'category_id' => 8,
                'name' => 'Saus Tiram Saori 250ml',
                'slug' => 'saus-tiram-saori-250ml',
                'description' => 'Saus tiram untuk penyedap tumisan dan masakan. Memberikan rasa gurih alami.',
                'price' => 16000,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/7/15/34567890-abcd-ef01-2345-678901234567.jpg',
            ],
            [
                'category_id' => 8,
                'name' => 'Royco Ayam 200g',
                'slug' => 'royco-ayam-200g',
                'description' => 'Bumbu penyedap rasa ayam. Membuat masakan lebih gurih dan lezat.',
                'price' => 12000,
                'stock' => 60,
                'min_stock' => 12,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/7/15/4567890a-bcde-f012-3456-789012345678.jpg',
            ],
            [
                'category_id' => 8,
                'name' => 'Masako Sapi 100g',
                'slug' => 'masako-sapi-100g',
                'description' => 'Bumbu kaldu sapi untuk penyedap masakan. Praktis dan ekonomis.',
                'price' => 6000,
                'stock' => 90,
                'min_stock' => 18,
                'is_active' => true,
                'image' => 'https://images.tokopedia.net/img/cache/500-square/VqbcmM/2021/7/15/567890ab-cdef-0123-4567-890123456789.jpg',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        echo "✅ " . count($products) . " products created successfully!\n";
    }
}
